### ISSUE TITLE
zabbix call failed

### ISSUE THREAD

**Issue by kylixtan** [dainis/terraform-provider-zabbix#2]
Error running plan: 1 error(s) occurred:
* provider.zabbix: -32600 (Invalid Request.): JSON-rpc version is not specified.

zabbix version: 2.4.3

thanks for your effort to upgrade the code

**Comment by dainis** [comment]
Could you share relevant parts from terraform file?

**Comment by kylixtan** [comment]
this is not a issue, just my config fault
