### ISSUE TITLE
Fork and License

### ISSUE THREAD

**Issue by xp-1000** [dainis/terraform-provider-zabbix#6]
Hello @dainis 

First, thanks for your work on this provider.

We forked your provider (and also the go lib from Aleski/Ouest-france) recently to be able to manage our templates on zabbix with terraform:
- https://github.com/claranet/terraform-provider-zabbix/
- https://github.com/claranet/go-zabbix-api

We planned to submit a PR to your original repo if you agree for that (while we use the ouest france go lib version and not the Aleski there is difference you could not want).

This is still work in progress but we should be ready soon to release a first minimal version to manage templates: 
- https://github.com/claranet/terraform-provider-zabbix/pull/7
- https://github.com/claranet/go-zabbix-api/pull/7

So we are at the point of the license question:
- While there is no License on your repo, are you agree and allow us to fork it ?
- If yes, we want to add a License on our fork (and on your repo when we will submit a PR) so do you have any preference or requirements ? Currently we propose an Apache v2 license.

I think the license question is priority but I think we can also use this issue in future to discuss how to submit a PR on your repo to integrate our new features ?

Thank you

**Comment by dainis** [comment]
Hi @xp-1000 

I have added license(MIT)

I have changed workplaces and I don't work with terraform anymore, so feel free to support this provider in your own fork
